[tools]
rojo = {source = "rojo-rbx/rojo", version = "6.0.2"}
remodel = {source = "rojo-rbx/remodel", version = "0.7.1"}
tarmac = {source = "Roblox/tarmac", version = "0.7.0"}
selene = {source = "Kampfkarren/selene", version = "0.11.0"}